// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  TongjiOauth200Response,
  Ping200Response,
  TongjiOauthTokenBodyRequest,
  TongjiOauthToken200Response,
  SessionHeaderRequest,
  Session200Response,
  SessionMessagesBodyRequest,
  SessionMessagesPathRequest,
  SessionMessagesHeaderRequest,
  SessionMessages200Response,
  SessionMessagesQueryRequest,
  TaskPlanPathRequest,
  TaskPlanHeaderRequest,
  TaskPlan200Response,
  TaskPlan404Response,
} from './namespaces';

export default class TongjiStudentService<T> {
  private request: any = () => {
    throw new Error('TongjiStudentService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 创建签名 `state` 并重定向到同济统一认证页面，作为浏览器授权流程入口 */
  TongjiOauthGET(req?: any, options?: T): Promise<TongjiOauth200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/tongji/oauth/authorize');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 健康检查 */
  PingGET(req?: any, options?: T): Promise<Ping200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/ping');
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** callback 页面提交 `code` 和 `state`，服务校验 state 后换取短期 Bearer access token */
  TongjiOauthTokenPOST(
    req: TongjiOauthTokenBodyRequest,
    options?: T,
  ): Promise<TongjiOauthToken200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/tongji/oauth/token');
    const method = 'POST';
    const data = { code: _req['code'], state: _req['state'] };
    const params = undefined;
    const headers = undefined;
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 创建一个新会话；可创建匿名临时会话，也可在携带有效校园 Bearer token 时创建认证持久会话 */
  SessionPOST(
    req: SessionHeaderRequest,
    options?: T,
  ): Promise<Session200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/sessions');
    const method = 'POST';
    const data = undefined;
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 向指定会话提交一轮用户消息，并通过 SSE 持续返回本轮执行事件与回答增量；响应为 `text/event-stream` */
  SessionMessagesPOST(
    req: SessionMessagesBodyRequest &
      SessionMessagesPathRequest &
      SessionMessagesHeaderRequest,
    options?: T,
  ): Promise<SessionMessages200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/sessions/{session_id}/messages');
    if (_req['session_id'] !== undefined && _req['session_id'] !== null) {
      url = url.replace('{session_id}', String(_req['session_id']));
    }
    const method = 'POST';
    const data = { message: _req['message'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 读取指定会话最近历史消息，结果按时间和消息序号从旧到新排列 */
  SessionMessagesGET(
    req: SessionMessagesQueryRequest &
      SessionMessagesPathRequest &
      SessionMessagesHeaderRequest,
    options?: T,
  ): Promise<SessionMessages200Response> {
    const _req = req || {};
    let url = this.genBaseURL(
      '/v1/sessions/{session_id}/messages-copy-1786359424',
    );
    if (_req['session_id'] !== undefined && _req['session_id'] !== null) {
      url = url.replace('{session_id}', String(_req['session_id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = { limit: _req['limit'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 读取指定会话当前活动任务计划；认证会话按当前 `user_id` 校验归属，匿名会话按 `session_id` capability 校验。当前不存在活动计划时返回 `{"plan":null}` */
  TaskPlanGET(
    req: TaskPlanPathRequest & TaskPlanHeaderRequest,
    options?: T,
  ): Promise<TaskPlan200Response & TaskPlan404Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/sessions/{session_id}/task-plan');
    if (_req['session_id'] !== undefined && _req['session_id'] !== null) {
      url = url.replace('{session_id}', String(_req['session_id']));
    }
    const method = 'GET';
    const data = undefined;
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }
}
