// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface Ping200Response {
  message: string;
}

export interface SessionHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface Session200Response {
  /** session 列表 */
  sessions: Session200ResponseSessionsItem[];
}

export interface Session200ResponseSessionsItem {
  /** session id */
  id: string;
  /** session 名 */
  name: string;
  /** 持久化类型，通常为 durable */
  persistence: string;
  /** 创建时间 */
  created_at: string;
  /** 最近 active 时间 */
  last_active_at: string;
}

export interface TaskPlanPathRequest {
  /** 目标会话 ID */
  session_id: string;
}

export interface TaskPlanHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface TaskPlan200Response {
  plan?: TaskPlan200ResponsePlanItem[];
}

export interface TaskPlan200ResponsePlanItem {
  /** 计划最近更新时间 */
  updated_at: string;
  /** 当前 session_id */
  session_id: string;
  /** 任务计划版本号，每次更新计划会递增 */
  revision: number;
  /** 任务列表 */
  tasks: TaskPlan200ResponsePlanItemTasksItem[];
}

export interface TaskPlan200ResponsePlanItemTasksItem {
  /** 任务唯一 ID */
  id: string;
  /** 任务描述 */
  desc: string;
  /** 任务状态： pending 、 in_progress 、 done 、 failed */
  status: string;
}

export interface TaskPlan404Response {
  error: string;
}

export interface TongjiOauth200Response {
  /** 302 跳转目标 URL，指向同济统一认证页面 */
  Location: string;
}

export interface UserBasicInfoHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface UserBasicInfo200Response {
  /** 用户姓名 */
  name: string;
  /** 学（工）号 */
  userId: string;
  /** 用户类型，如本科生 */
  userTypeName: string;
}

export interface SessionHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface SessionBodyRequest {
  /** session 名 */
  name?: string;
}

export interface Session200Response {
  /** 会话 ID；匿名会话通常为 `anon_` 前缀 */
  session_id: string;
  /** 会话持久化类型，取值为 `ephemeral` 或 `durable` */
  persistence: string;
}

export interface SessionMessagesPathRequest {
  /** 目标会话 ID */
  session_id: string;
}

export interface SessionMessagesHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface SessionMessagesBodyRequest {
  /** 本轮用户输入，不能为空字符串 */
  message: string;
  /** 模型档位，只允许：lite、pro、max；缺省时默认为 lite */
  model_tier?: string;
}

export interface SessionMessages200Response {
  /** 事件类型，可选值包括 run.started、agent.status、assistant.reasoning、assistant.delta、tool.call.started、tool.call.completed、tool.call.failed、task_plan.updated、run.completed、run.failed */
  type: string;
  /** 本轮次 run_id */
  run_id: string;
  /** 当前 session_id */
  session_id: string;
  /** 事件的顺序编号，从 1 开始递增计数 */
  seq: number;
  /** 当前时间戳 */
  occurred_at: string;
  /** 业务 data */
  data: any;
}

export interface SessionRenameHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization?: string;
}

export interface SessionRenameBodyRequest {
  /** session id */
  session_id: string;
  /** 新 session 名 */
  name: string;
}

export interface SessionRename200Response {
  /** session id */
  id: string;
  /** session 名 */
  name: string;
  /** 持久化类型，通常为 durable */
  persistence: string;
  /** 创建时间 */
  created_at: string;
  /** 最近 active 时间 */
  last_active_at: string;
}

export interface TongjiOauthTokenBodyRequest {
  /** 同济开放平台回调附带的授权码 */
  code: string;
  /** 授权阶段签发并回传的 state，用于防篡改校验 */
  state: string;
}

export interface TongjiOauthToken200Response {
  /** 当前浏览器会话使用的短期 Bearer token */
  access_token: string;
  /** Token 类型 */
  token_type: string;
  /** token 过期时间，单位秒 */
  expires_in: number;
  /** 当前 token 的 scope */
  scope: string;
}

export interface SessionDeleteHeaderRequest {
  /** 认证会话传 `Bearer <access_token>`；匿名会话可不传 */
  Authorization: string;
}

export interface SessionDeleteBodyRequest {
  /** session id */
  session_id: string;
}

export interface SessionMessagesQueryRequest {
  /** 本页返回消息数，范围 1..100。前端推荐使用 50。 */
  limit?: number;
  /** 从快照中最新消息开始跳过的消息数，必须大于等于 0。 */
  offset?: number;
  /** 首次请求响应中的快照最大消息序号；后续所有页原样传回。 */
  snapshot_sequence?: number;
}

export interface SessionMessagesPathRequest {
  /** 目标会话 ID */
  session_id: string;
}

export interface SessionMessagesHeaderRequest {
  /** 认证会话使用 Bearer <access_token>；匿名会话不传。 */
  Authorization?: string;
}

export interface SessionMessages200Response {
  /** 本页消息列表；按 sequence 升序排列。 */
  messages: SessionMessages200ResponseMessagesItem[];
  /** 在当前快照内是否仍有更早消息可读取。 */
  has_more: boolean;
  /** 本次读取固定使用的最大消息序号。后续分页必须携带。 */
  snapshot_sequence: number;
}

export interface SessionMessages200ResponseMessagesItem {
  /** 所属对话轮次/运行 ID。相同 run_id 的消息属于同一轮。 */
  run_id: string;
  /** 会话内连续递增的消息序号，从 1 开始。 */
  sequence: number;
  /** 消息角色：user、assistant 或 tool。 */
  role: string;
  /** 消息正文；工具消息通常为工具执行结果 JSON 文本。 */
  content: string;
  /** 创建时间，RFC 3339 UTC 时间戳。 */
  created_at: string;
  /** assistant 消息发起的工具调用列表。 */
  tool_calls?: SessionMessages200ResponseMessagesItemTool_callsItem[];
  /** 该消息对应的模型档位，只支持：lite、pro、max。 */
  model_tier?: string;
  /** 该消息对应的模型 id。 */
  model_id?: string;
  /** 消息唯一 ID。 */
  id: string;
  /** tool 消息对应的工具调用 ID。 */
  tool_call_id?: string;
  /** tool 消息对应的工具名称。 */
  tool_name?: string;
  /** assistant 的模型思考内容。 */
  reasoning_content?: string;
  /** assistant 消息的 Responses API response ID。 */
  response_id?: string;
  /** assistant response 缓存到期时间戳。 */
  response_cache_expires_at?: number;
  /** 所属会话 ID。 */
  session_id: string;
}

export interface SessionMessages200ResponseMessagesItemTool_callsItem {
  /** 同一 assistant 消息内的工具调用顺序。 */
  index: number;
  /** 工具调用类型，如 function_call。 */
  type: string;
  /** 函数型工具调用详情。 */
  function?: SessionMessages200ResponseMessagesItemTool_callsItemFunction;
  /** 工具调用 ID；tool 消息的 tool_call_id 对应此值。 */
  id: string;
}

export interface SessionMessages200ResponseMessagesItemTool_callsItemFunction {
  /** 工具/函数名称。 */
  name: string;
  /** 工具参数的 JSON 字符串。 */
  arguments: string;
}
